name: game_core
description: The Orchestrator for the sozzle game
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  level_data:
    path: ../level_data

dev_dependencies:
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
