name: sozzle
description: Sozzle a word puzzle game made with Fluttter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^1.1.1
  bloc: ^8.1.0
  circular_pattern: ^0.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^4.5.0
  grid_board:
    git:
      url: https://github.com/agtrlabs/grid_board.git
      ref: main
  http: ^0.13.5
  intl: ^0.17.0
  localstore: ^1.2.3

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sfx/
