name: sozzle
description: Sozzle a word puzzle game made with Fluttter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.3
  audioplayers: ^6.5.1
  awesome_dialog: ^3.2.1
  bloc: ^8.1.4
  circular_pattern: ^0.1.1
  device_preview: ^1.3.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  game_core:
    path: packages/game_core
  go_router: ^16.2.1
  grid_board:
    git:
      url: https://github.com/agtrlabs/grid_board.git
      ref: main
  http: ^1.5.0
  hydrated_bloc: ^9.1.5
  intl: ^0.20.2
  level_data:
    path: packages/level_data
  level_generator:
    path: packages/level_generator
  localstore: ^1.4.0
  path_provider: ^2.1.5
  rive: ^0.14.0-dev.11
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sfx/
    - assets/rive/
    - assets/icons/
